# konsistensi_1_f

persekolahan:
  persekolahan_01_01:
    'P': 1
    'PT': '93'
    'U': range(0, 8)
    'SJ': '01'

  persekolahan_01_02:
    'P': 1
    'PT': '92'
    'U': range(9, 200)
    'SJ': '03'

  persekolahan_01_03:
    'P': 1
    'PT': '91'
    'U': range(3, 200)
    'SJ': '03'

  persekolahan_02_01:
    'P': 2
    'PT': ['1', '2']
    'U': range(4, 6)
    'SJ': '20'

  persekolahan_02_02:
    'P': 2
    'PT': ['11', '12', '13', '14', '15']
    'U': range(5, 13)
    'SJ': '20'

  persekolahan_02_03:
    'P': 2
    'PT': '16' 
    'U': range(10, 14)
    'SJ': ['20', '11', '12'] 

  persekolahan_02_04:
    'P': 2
    'PT': '21'
    'U': range(11, 14)
    'SJ': '12'
    
  persekolahan_02_05:
    'P': 2
    'PT': ['22', '23']
    'U': range(11, 16)
    'SJ': ['20', '11', '12']

  persekolahan_02_06:
    'P': 2
    'PT': '24'
    'U': range(13, 17)
    'SJ': ['20', '11', '12', '21', '22']

  persekolahan_02_07:
    'P': 2
    'PT': '31'
    'U': range(14, 18)
    'SJ': ['20', '21', '22', '31'] 

  persekolahan_02_08:
    'P': 2
    'PT': '32'
    'U': range(15, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']
    
  persekolahan_02_09:
    'P': 2
    'PT': '33'
    'U': range(15, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_02_10:
    'P': 2
    'PT': '208'
    'U': range(15, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_02_11:
    'P': 2
    'PT': '209'
    'U': range(15, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36'] 

  persekolahan_02_12:
    'P': 2
    'PT': '41'
    'U': range(16, 40)
    'SJ': ['31', '32', '33', '34', '35', '36', '41']

  persekolahan_02_13:
    'P': 2
    'PT': '42'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43']

  persekolahan_02_14:
    'P': 2
    'PT': '43'
    'U': range(17, 21)
    'SJ': ['22', '31', '32', '33', '34', '35', '44']

  persekolahan_02_15:
    'P': 2
    'PT': '304'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43', '44'] 

  persekolahan_02_16:
    'P': 2
    'PT': '305'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43', '44']

  persekolahan_02_17:
    'P': 2
    'PT': '306'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34']

  persekolahan_02_18:
    'P': 2
    'PT': '307'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34']

  persekolahan_02_19:
    'P': 2
    'PT': '308'
    'U': range(17, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36'] 

  persekolahan_02_20:
    'P': 2
    'PT': '309'
    'U': range(17, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_02_21:
    'P': 2
    'PT': '310'
    'U': range(17, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']

  persekolahan_02_22:
    'P': 2
    'PT': '311'
    'U': range(17, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']

  persekolahan_02_23:
    'P': 2
    'PT': '51'
    'U': range(17, 70)
    'SJ': ['21', '22', '31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51'] 

  persekolahan_02_24:
    'P': 2
    'PT': ['61', '62', '63']
    'U': range(17, 70)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65']

  persekolahan_02_25:
    'P': 2
    'PT': '64'
    'U': range(17, 70)
    'SJ': ['33', '51', '71']

  persekolahan_02_26:
    'P': 2
    'PT': '65'
    'U': range(17, 70)
    'SJ': ['71', '72']

  persekolahan_02_27:
    'P': 2
    'PT': ['66', '67']
    'U': range(17, 70)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65', '81', '82', '83', '84'] 

  persekolahan_02_28:
    'P': 2
    'PT': '71'
    'U': range(17, 80)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '71', '72', '81', '82', '83', '84', '91']
    
  persekolahan_02_29:
    'P': 2
    'PT': '72'
    'U': range(20, 80)
    'SJ': ['91', '92'] 

  persekolahan_02_30:
    'P': 2
    'PT': '73'
    'U': range(20, 80)
    'SJ': ['91', '92', '93']

  persekolahan_02_31:
    'P': 2
    'PT': '81'
    'U': range(21, 80)
    'SJ': ['91', '92', '93', '94']

  persekolahan_02_32:
    'P': 2
    'PT': '82'
    'U': range(21, 80)
    'SJ': ['94', '95']

  persekolahan_02_33:
    'P': 2
    'PT': '6'
    'U': range(3, 200)
    'SJ': ['21', '11', '12', '21', '22', '31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65', '71', '72', '81', '82', '83', '84', '91', '92', '93', '94', '95']
    
  persekolahan_03_01:
    'P': 3
    'PT': '31'
    'U': range(14, 18)
    'SJ': ['20', '21', '22', '31']

  persekolahan_03_02:
    'P': 3
    'PT': '32'
    'U': range(15, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34']

  persekolahan_03_03:
    'P': 3
    'PT': '33' 
    'U': range(15, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36'] 

  persekolahan_03_04:
    'P': 3
    'PT': '41'
    'U': range(16, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36'] 
    
  persekolahan_03_05:
    'P': 3
    'PT': '42'
    'U': range(17, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_03_06:
    'P': 3
    'PT': '51'
    'U': range(15, 70)
    'SJ': ['31', '32', '33', '34', '35', '36', '51', '41']

  persekolahan_03_07:
    'P': 3
    'PT': ['61', '62', '63']
    'U': range(17, 70)
    'SJ': ['31', '32', '32', '33', '34', '35', '36', '51', '41', '42', '43'] 

  persekolahan_03_08:
    'P': 3
    'PT': '64'
    'U': range(17, 70)
    'SJ': ['22', '31', '32', '33', '34', '35', '44']
    
  persekolahan_03_09:
    'P': 3
    'PT': '65' 
    'U': range(17, 70)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43', '44'] 

  persekolahan_03_10:
    'P': 3
    'PT': ['66', '67']
    'U': range(17, 70)
    'SJ': ['31', '32', '33', '34', '35', '36', '51', '41', '42', '43', '44']
    
  persekolahan_03_11:
    'P': 3
    'PT': '71'
    'U': range(17, 80)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '71', '72', '81', '82', '83', '84', '91']

  persekolahan_03_12:
    'P': 3
    'PT': '72'
    'U': range(20, 80)
    'SJ': ['91', '92']
    
  persekolahan_03_13:
    'P': 3
    'PT': '73' 
    'U': range(20, 80)
    'SJ': ['91', '92', '93'] 

  persekolahan_03_14:
    'P': 3
    'PT': '81'
    'U': range(21, 80)
    'SJ': ['91', '92', '93', '94']
    
  persekolahan_03_15:
    'P': 3
    'PT': '82'
    'U': range(21, 80)
    'SJ': ['94', '95']

  persekolahan_03_16:
    'P': 3
    'PT': '6'
    'U': range(3, 200)
    'SJ': ['21', '11', '12', '21', '22', '31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65', '71', '72', '81', '82', '83', '84', '91', '92', '93', '94', '95']
    
  persekolahan_04_01:
    'P': 4
    'PT': '2'
    'U': range(5, 200)
    'SJ': '20'

  persekolahan_04_02:
    'P': 4
    'PT': ['11', '12', '13', '14']
    'U': range(6, 200)
    'SJ': '20'

  persekolahan_04_03:
    'P': 4
    'PT': ['15', '16'] 
    'U': range(10, 200)
    'SJ': ['20', '11', '12'] 

  persekolahan_04_04:
    'P': 4
    'PT': '21'
    'U': range(12, 200)
    'SJ': '12'
    
  persekolahan_04_05:
    'P': 4
    'PT': ['22', '23']
    'U': range(12, 200)
    'SJ': ['20', '11', '12']

  persekolahan_04_06:
    'P': 4
    'PT': '24'
    'U': range(14, 200)
    'SJ': ['20', '11', '12', '21', '22']

  persekolahan_04_07:
    'P': 4
    'PT': '31' 
    'U': range(15, 200)
    'SJ': ['20', '21', '22', '31'] 

  persekolahan_04_08:
    'P': 4
    'PT': '32'
    'U': range(16, 200)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']  
    
  persekolahan_04_09:
    'P': 4
    'PT': '33'
    'U': range(15, 200)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_04_10:
    'P': 4
    'PT': '208'
    'U': range(15, 200)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_04_11:
    'P': 4
    'PT': '209' 
    'U': range(15, 200)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_04_12:
    'P': 4
    'PT': '41'
    'U': range(17, 200)
    'SJ': ['31', '32', '33', '34', '35', '36', '41']
    
  persekolahan_04_13:
    'P': 4
    'PT': '42'
    'U': range(18, 200)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43']

  persekolahan_04_14:
    'P': 4
    'PT': '43'
    'U': range(17, 200)
    'SJ': ['22', '31', '32', '33', '34', '35', '44']

  persekolahan_04_15:
    'P': 4
    'PT': '401' 
    'U': range(17, 200)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43', '44']

  persekolahan_04_16:
    'P': 4
    'PT': '51'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34', '35', '36', '41', '42', '43', '44']
    
  persekolahan_04_17:
    'P': 4
    'PT': '305'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34']

  persekolahan_04_18:
    'P': 4
    'PT': '306'
    'U': range(17, 40)
    'SJ': ['31', '32', '33', '34']

  persekolahan_04_19:
    'P': 4
    'PT': '307' 
    'U': range(17, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']

  persekolahan_04_20:
    'P': 4
    'PT': '308'
    'U': range(17, 40)
    'SJ': ['20', '11', '12', '21', '22', '31', '32', '33', '34', '35', '36']    
    
  persekolahan_04_21:
    'P': 4
    'PT': '309'
    'U': range(17, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']

  persekolahan_04_22:
    'P': 4
    'PT': '310'
    'U': range(17, 40)
    'SJ': ['20', '21', '22', '31', '32', '33', '34', '35']

  persekolahan_04_23:
    'P': 4
    'PT': '311' 
    'U': range(17, 40)
    'SJ': ['21', '22', '31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51']

  persekolahan_04_24:
    'P': 4
    'PT': ['61', '62', '63']
    'U': range(17, 200)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '91']
    
  persekolahan_04_25:
    'P': 4
    'PT': '64'
    'U': range(17, 200)
    'SJ': ['33', '51', '71']

  persekolahan_04_26:
    'P': 4
    'PT': '65'
    'U': range(17, 200)
    'SJ': ['71', '72']

  persekolahan_04_27:
    'P': 4
    'PT': ['66', '67']
    'U': range(17, 200)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65', '81', '82', '83', '84']

  persekolahan_04_28:
    'P': 4
    'PT': '71'
    'U': range(17, 200)
    'SJ': ['31', '32', '33', '34', '35', '41', '42', '43', '44', '71', '72', '81', '82', '83', '84', '91']      
    
  persekolahan_04_29:
    'P': 4
    'PT': '72'
    'U': range(21, 200)
    'SJ': ['91', '92']

  persekolahan_04_30:
    'P': 4
    'PT': '73'
    'U': range(21, 200)
    'SJ': ['91', '92', '93']

  persekolahan_04_31:
    'P': 4
    'PT': '81'
    'U': range(21, 200)
    'SJ': ['91', '92', '93', '94']

  persekolahan_04_32:
    'P': 4
    'PT': '82'
    'U': range(21, 200)
    'SJ': ['94', '95']
    
  persekolahan_04_33:
    'P': 4
    'PT': '6'
    'U': range(3, 200)
    'SJ': ['21', '11', '12', '21', '22', '31', '32', '33', '34', '35', '41', '42', '43', '44', '36', '51', '61', '62', '63', '64', '65', '71', '72', '81', '82', '83', '84', '91', '92', '93', '94', '95']    